imagePullPolicy: Always
nameOverride: ""
fullnameOverride: ""
rbacEnabled: true
# The DAGSTER_HOME env var is set by default on all nodes from this value
dagster_home: "/opt/dagster/dagster_home"

####################################################################################################
# Dagit: Configuration for the Dagit webserver
####################################################################################################
dagit:
  replicaCount: 1
  # REQUIRED: Dagit image repository and tag to deploy
  image:
    repository: ""
    tag: ""

  service:
    type: ClusterIP
    port: 80

  # Can be set to override the default dagster home on the dagit containers
  dagster_home: ""
  # Additional environment variables to set on the dagit container.
  # A Kubernetes ConfigMap will be created with these environment variables.
  env:
    YOUR_ENV_VAR: ""
  # Additional environment variables can be retrieved and set from the ConfigMaps enumerated as a
  # list here
  env_config_maps:
    - ""
  # Additional (secret) environment variables can be retrieved and set from the Secrets enumerated
  # as a list here
  env_secrets:
    - ""
  # Support Node, affinity and tolerations for Dagit pod assignment. See:
  # https://kubernetes.io/docs/concepts/configuration/assign-pod-node/#nodeselector
  # https://kubernetes.io/docs/concepts/configuration/assign-pod-node/#affinity-and-anti-affinity
  # https://kubernetes.io/docs/concepts/configuration/taint-and-toleration/
  nodeSelector: {}
  affinity: {}
  tolerations: []
  podSecurityContext: {}
  securityContext: {}
  resources:
    {}
  # If you want to specify resources, uncomment the following lines, adjust them as necessary,
  # and remove the curly braces after 'resources:'.
  # limits:
  #   cpu: 100m
  #   memory: 128Mi
  # requests:
  #   cpu: 100m
  #   memory: 128Mi

####################################################################################################
# Job Runner: Configuration for the celery/job containers, which together handle physical execution
####################################################################################################
job_runner:
  # REQUIRED: The Dagster K8sRunLauncher will invoke job executions in containers running this image
  image:
    repository: ""
    tag: ""
  # Can be set to override the default dagster home on the celery/job containers
  dagster_home: ""
  # Additional environment variables to set on the celery/job containers
  # A Kubernetes ConfigMap will be created with these environment variables.
  env:
    YOUR_ENV_VAR: ""
  # Additional environment variables can be retrieved and set from the ConfigMaps enumerated as a
  # list here
  env_config_maps:
    - ""
  # Additional (secret) environment variables can be retrieved and set from the Secrets enumerated
  # as a list here
  env_secrets:
    - ""

####################################################################################################
# PostgreSQL: Configuration values for postgresql
#
# https://github.com/kubernetes/charts/blob/master/stable/postgresql/README.md
#
# A PostgreSQL database is required to run Dagster on Kubernetes. If postgresql.enabled is marked as
# false, the PG credentials specified here will still be used, and should point to an external PG
# database that is accessible from this chart.
####################################################################################################
postgresql:
  # set postgresql.enabled to be false to disable deploy of a PostgreSQL database and use an
  # existing external PostgreSQL database
  enabled: true
  # set this PostgreSQL hostname when using an external PostgreSQL database
  postgresqlHost: ""
  postgresqlUsername: test
  # Note when changing this password (e.g. in test) that credentials will
  # persist as long as the PVCs do -- see:
  # https://github.com/helm/charts/issues/12836#issuecomment-524552358
  postgresqlPassword: test
  postgresqlDatabase: test
  service:
    port: 5432

####################################################################################################
# Celery
####################################################################################################
celery:
  enabled: true
  # support overriding the name of Celery workers
  workers:
    nameOverride: ""
  # Number of replicas for the default Celery queue
  replicaCount: 5
  # additional config options for Celery, applied to all queues. See:
  # https://docs.celeryproject.org/en/stable/userguide/configuration.html for available options
  configSource:
  # additional Celery worker queues can be configured here. Off by default.
  extraWorkerQueues:
    # Each additional queue specified will be provisioned as an additional deployment alongside the
    # default Celery worker deployment.
    # Example:
    # - name: "redshift"
    #   replicaCount: "3"
  # Support Node, affinity and tolerations for Celery pod assignment. See:
  # https://kubernetes.io/docs/concepts/configuration/assign-pod-node/#nodeselector
  # https://kubernetes.io/docs/concepts/configuration/assign-pod-node/#affinity-and-anti-affinity
  # https://kubernetes.io/docs/concepts/configuration/taint-and-toleration/
  nodeSelector: {}
  affinity: {}
  tolerations: []
  podSecurityContext: {}
  securityContext: {}
  resources:
    {}
  # If you want to specify resources, uncomment the following lines, adjust them as necessary,
  # and remove the curly braces after 'resources:'.
  # limits:
  #   cpu: 100m
  #   memory: 128Mi
  # requests:
  #   cpu: 100m
  #   memory: 128Mi

####################################################################################################
# RabbitMQ: Configuration values for rabbitmq. Only one of RabbitMQ / Redis should be enabled.
####################################################################################################
rabbitmq:
  enabled: true
  rabbitmq:
    username: test
    password: test
  service:
    port: 5672
  # https://github.com/helm/charts/issues/17250#issuecomment-533444837
  volumePermissions:
    enabled: true

####################################################################################################
# Redis: Configuration values for Redis. Can be used instead of RabbitMQ.
####################################################################################################
redis:
  # if enabled, external redis will be used instead of rabbitmq
  enabled: false
  # Redis host URL
  host: ""
  # Redis port
  port: 6379
  # Set DB number for Redis broker DB (default 0)
  brokerDbNumber:
  # Set DB number for Redis backend DB (default 0)
  backendDbNumber:

####################################################################################################
# Flower: (Optional) The flower web interface for diagnostics and debugging Celery queues & workers
####################################################################################################
flower:
  enabled: true
  service:
    annotations:
    port:
  # Support Node, affinity and tolerations for Flower pod assignment. See:
  # https://kubernetes.io/docs/concepts/configuration/assign-pod-node/#nodeselector
  # https://kubernetes.io/docs/concepts/configuration/assign-pod-node/#affinity-and-anti-affinity
  # https://kubernetes.io/docs/concepts/configuration/taint-and-toleration/
  nodeSelector: {}
  affinity: {}
  tolerations: []
  podSecurityContext: {}
  securityContext: {}
  resources:
    {}
  # If you want to specify resources, uncomment the following lines, adjust them as necessary,
  # and remove the curly braces after 'resources:'.
  # limits:
  #   cpu: 100m
  #   memory: 128Mi
  # requests:
  #   cpu: 100m
  #   memory: 128Mi

####################################################################################################
# Ingress: (Optional) Create ingresses for Dagit and Flower
####################################################################################################
ingress:
  enabled: false
  annotations: {}
  dagit:
    # Ingress hostname for Dagit e.g. dagit.mycompany.com
    # NOTE: Dagit doesn't yet support hosting on a path, e.g. mycompany.com/dagit
    # See: https://github.com/dagster-io/dagster/issues/2073
    host: ""
    precedingPaths:
      # Different http paths to add to the ingress before the default dagit path
      # Example:
      # - path: "/*"
      #   serviceName: "ssl-redirect"
      #   servicePort: "use-annotation"
    succeedingPaths:
      # Different http paths to add to the ingress after the default dagit path
      # Example:
      # - path: "/*"
      #   serviceName: "ssl-redirect"
      #   servicePort: "use-annotation"
  flower:
    # Ingress hostname for Dagit e.g. flower.mycompany.com
    host: ""
    # if path is '/flower', Flower will be accessible at 'mycompany.com/flower'
    # NOTE: do NOT keep trailing slash. For root configuration, set as empty string
    path: ""
    precedingPaths:
      # Different http paths to add to the ingress before the default flower path
      # Example:
      # - path: "/*"
      #   serviceName: "ssl-redirect"
      #   servicePort: "use-annotation"
    succeedingPaths:
      # Different http paths to add to the ingress after the default flower path
      # Example:
      # - path: "/*"
      #   serviceName: "ssl-redirect"
      #   servicePort: "use-annotation"


####################################################################################################
# Extra Manifests: (Optional) Create additional k8s resources within this chart
####################################################################################################
extraManifests:
##
## Example:
##  - apiVersion: cloud.google.com/v1beta1
##    kind: BackendConfig
##    metadata:
##      name: "{{ .Release.Name }}-backend-config"
##      labels:
##      {{- include "dagster.labels" . | nindent 6 }}
##    spec:
##      securityPolicy:
##        name: "gcp-cloud-armor-policy-test"


serviceAccount:
  create: true
